### PR TITLE
keyword explorer reports

### LINKED ISSUE #1: ahrefs automation - keyword explorer reports
Explainer: https://www.loom.com/share/9a5fbbb83107463fb5447e552180ac49

Original code file to start from: https://github.com/serpcompany/dev-malik/blob/main/ahrefs_batch_analysis.py

Note: sometimes these keywords have commas in them. that will mess up the keywords processing. can we make some logic that will ensure any commas in the file get removed before the automation starts? @ammarbinfaisal

### PR DESCRIPTION
**Pull request by ammarbinfaisal**
fixes #1

### CODE REVIEW

**Comment by devinschumacher** [comment]
@ammarbinfaisal @ammarbinfaisal is this supposed to be an extension of the previous file, or a separate file? 

im not seeing any logic in it for choosing to run "keywords explorer" vs. "batch analysis"

it just asks for accounts vs. posts like normal

**Comment by ammarbinfaisal** [comment]
@devinschumacher I made a separate file `ahrefs_keyword_analysis.py`. Let me incorporate that logic in the previous file.

**Comment by devinschumacher** [comment]
okay! you dont have to do that i just must have missed that file @ammarbinfaisal

**Review by devinschumacher — CHANGES_REQUESTED** [review]
there is a bug in the batching logic that you can see in [this video](https://www.loom.com/share/007a4d097efc40c78d8d6b3264fe628d)

should we generate some unit tests for this kind of situation?

thx

**Review by devinschumacher — APPROVED** [review]

**Pull request merged**
